#!/bin/bash
#
# Provisioning script for Stratio Sandbox.
# More info at https://github.com/Stratio/sandbox
#


##############
## SERVICES ##
##############

echo -e 'Installing Stratio Ingestion...'

yum_install stratio-ingestion

echo -e 'Installing Apache HTTPD 2 server...'
yum_install httpd
chkconfig httpd on
service httpd restart

echo -e 'Enabling ElasticSearch...'
chkconfig elasticsearch on
service elasticsearch restart

##############
## EXAMPLES ##
##############

echo -e 'Installing unzip...'
yum_install unzip

echo -e 'Installing examples...'
#FIXME: This should be part of the Ingestion package
TMPDIR=$(mktemp --directory)
cd "${TMPDIR}"
download "https://github.com/Stratio/flume-ingestion/zipball/develop" "flume-ingestion.zip"
unzip -qq flume-ingestion.zip
cp -rf Stratio-flume-ingestion*/examples /opt/sds/ingestion/

############
## KIBANA ##
############

KIBANA_VERSION=3.1.2
KIBANA_INSTALL=/var/www/html
KIBANA_TARBALL="kibana-${KIBANA_VERSION}.tar.gz"
KIBANA_DOWNLOAD_URL="https://download.elasticsearch.org/kibana/kibana/${KIBANA_TARBALL}"

if [ ! -e "/var/www/html/kibana" ]; then
	echo -e 'Downloading Kibana...'
	mkdir -p "${DOWNLOADS_DIR}"
	download "${KIBANA_DOWNLOAD_URL}" "${DOWNLOADS_DIR}/${KIBANA_TARBALL}"
	echo -e 'Extracting Kibana...'
	mkdir -p "${KIBANA_INSTALL}"
	cd "${KIBANA_INSTALL}"
	tar xf "${DOWNLOADS_DIR}/${KIBANA_TARBALL}"
	ln -s kibana-${KIBANA_VERSION} kibana
fi

################
## NODE & NPM ##
################
echo -e 'Installing Node.js'
yum_install nodejs npm --enablerepo=epel

##############
## KIBANA 4 ##
##############

KIBANA_4_VERSION=4.0.2
KIBANA_4_INSTALL=/opt/sds
KIBANA_4_TARBALL="kibana-${KIBANA_4_VERSION}-linux-x64.tar.gz"
KIBANA_4_DOWNLOAD_URL="https://download.elastic.co/kibana/kibana/${KIBANA_4_TARBALL}"

echo -e 'Downloading Kibana 4...'
mkdir -p "${DOWNLOADS_DIR}"
download "${KIBANA_4_DOWNLOAD_URL}" "${DOWNLOADS_DIR}/${KIBANA_4_TARBALL}"
echo -e 'Extracting Kibana 4...'
cd "${KIBANA_4_INSTALL}"
tar xf "${DOWNLOADS_DIR}/${KIBANA_4_TARBALL}"
echo -e 'Starting Kibana 4...'
./${KIBANA_4_INSTALL}/kibana-${KIBANA_4_VERSION}-linux-x64/kibana &

#################
## ELASTICDUMP ##
#################
echo -e 'Installing elasticdump'
sudo npm install elasticdump -g

#######################
## KIBANA DASHBOARDS ##
#######################

echo -e 'Installing Kibana dashboards...'
cp -f /opt/sds/ingestion/examples/*/dashboards/*.json "${KIBANA_INSTALL}/kibana/app/dashboards"
chmod -R 777 "${KIBANA_INSTALL}/kibana/app/dashboards"

#########################
## KIBANA 4 DASHBOARDS ##
#########################

echo -e 'Installing Kibana 4 dashboards...'
#elasticdump --input /opt/sds/ingestion/examples/airlines-map/dashboards/us-flights.json --output=http://localhost:9200/.kibana --type=data

