ITSERVICES:
  - ZOOKEEPER:
      image: stratio/zookeeper:3.4.6
  - MONGODB:
      image: stratio/mongo:3.0.4
      sleep: 10
  - ELASTICSEARCH:
      image: stratio/elasticsearch:1.7.1
      sleep: 5
      env:
        - CLUSTER_NAME=%%JUID
  - CASSANDRA:
      image: stratio/cassandra-lucene-index:2.2.5.3
      sleep: 10
      env:
        - MAX_HEAP=256M
  - KAFKA:
      image: stratio/kafka:0.8.2.1
      env:
        - ZOOKEEPER_HOSTS=%%ZOOKEEPER:2181

ITPARAMETERS: >
    -Dzookeeper.hosts.0=%%ZOOKEEPER:2181
    -Dkafka.hosts.0=%%KAFKA:9092
    -Dmongo.hosts.0=%%MONGODB:27017
    -Dcassandra.hosts.0=%%CASSANDRA:9042
    -Delasticsearch.hosts.0=%%ELASTICSEARCH:9300
    -Delasticsearch.clusterName=%%JUID