language: java
jdk:
  - oraclejdk7
cache:
  directories:
    - $HOME/.m2
install:
  - sudo apt-get update
  - sudo apt-get install -y -q rpm
  - mvn install -B -q -DskipUTs -DskipITs
script:
  - mvn test -Ptravis-test
  - mvn package -B -q -Ppackage -DskipUTs -DskipITs
