# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = "stratiodemo"

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. See: vagrantup.com.

  # Build against Ubuntu Trusty 64
  config.vm.box = "ubuntu/trusty64"

  # Enable host-only access to the machine using a specific IP.
  #config.vm.network :private_network, ip: "192.168.33.34"

  # Shared folders.
  # You can only use NFS (second option below) once nfs-utils is installed.
  # config.vm.synced_folder "/path/to/local/folder", "/path/to/remote"
  # config.vm.synced_folder "/path/to/local/folder", "/path/to/remote",
  # :nfs => !RUBY_PLATFORM.downcase.include?("w32"),
  # id: "share"

  # Provider-specific configuration for VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--name", NAME]
    #v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    #ansible.inventory_path = "provisioning/inventory"
    # Run commands as root.
    ansible.sudo = true
    ansible.verbose = 'vvvv'
    # ansible.raw_arguments = ['-v']
  end

  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define :stratiodemo do |stratiodemo|
    stratiodemo.vm.hostname = NAME
  end

end
