#!/bin/sh
# Copyright (c) 2015 Stratio (http://stratio.com)
#

set -e

GROUP='stratio'
USER='ingestion'
DIR_INSTALL='/opt/sds/ingestion'
DIR_CONF='/etc/sds/ingestion'
DIR_LOG='/var/log/sds/ingestion'
DIR_RUN='/var/run/sds'

# Add stratio group if it doesn't already exists
if ! getent group $GROUP >/dev/null 2>&1; then
groupadd ${GROUP}
fi

# Add stratio user if it doesn't already exists
if ! getent passwd $USER >/dev/null 2>&1; then
[ -d /opt ] || mkdir /opt
useradd -M -d /opt/sds -g ${GROUP} -s /bin/bash ${USER}
else
usermod -G $GROUP $USER
fi

if [ ! -d "$DIR_LOG" ]; then
mkdir $DIR_LOG
fi
chown -R ${USER}:${GROUP} $DIR_LOG
chmod 775 $DIR_LOG

chown -R ${USER}:${GROUP} $DIR_INSTALL
chmod -R 775 $DIR_INSTALL

if [ ! -d "$DIR_CONF" ]; then
mkdir $DIR_CONF
fi
chown -R ${USER}:${GROUP} $DIR_CONF

if [ ! -d "$DIR_RUN" ]; then
mkdir $DIR_RUN
fi
chown -R ${USER}:${GROUP} $DIR_RUN
chmod 0775 $DIR_RUN

chmod 0755 $DIR_INSTALL/bin/*
chmod 0755 $DIR_INSTALL/examples/*/bin/*
chmod +x /etc/default/ingestion*


/sbin/chkconfig --add ingestion

